/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EloRouteImport } from './routes/elo'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ApiEloSyncRouteImport } from './routes/api.elo-sync'
import { Route as ApiSportsApiMaintenanceRouteImport } from './routes/api.sports-api-maintenance'
import { Route as ApiSportsDailySyncRouteImport } from './routes/api.sports-daily-sync'
import { Route as ApiSportsJobsRouteImport } from './routes/api.sports-jobs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EloRoute = EloRouteImport.update({
  id: '/elo',
  path: '/elo',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEloSyncRoute = ApiEloSyncRouteImport.update({
  id: '/api/elo-sync',
  path: '/api/elo-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsApiMaintenanceRoute = ApiSportsApiMaintenanceRouteImport.update({
  id: '/api/sports-api-maintenance',
  path: '/api/sports-api-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsDailySyncRoute = ApiSportsDailySyncRouteImport.update({
  id: '/api/sports-daily-sync',
  path: '/api/sports-daily-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsJobsRoute = ApiSportsJobsRouteImport.update({
  id: '/api/sports-jobs',
  path: '/api/sports-jobs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anotacoes': typeof AnotacoesRoute
  '/conta': typeof ContaRoute
  '/elo': typeof EloRoute
  '/hoje': typeof HojeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/api/sports-api-maintenance': typeof ApiSportsApiMaintenanceRoute
  '/api/sports-daily-sync': typeof ApiSportsDailySyncRoute
  '/api/sports-jobs': typeof ApiSportsJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anotacoes': typeof AnotacoesRoute
  '/conta': typeof ContaRoute
  '/elo': typeof EloRoute
  '/hoje': typeof HojeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/api/sports-api-maintenance': typeof ApiSportsApiMaintenanceRoute
  '/api/sports-daily-sync': typeof ApiSportsDailySyncRoute
  '/api/sports-jobs': typeof ApiSportsJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anotacoes': typeof AnotacoesRoute
  '/conta': typeof ContaRoute
  '/elo': typeof EloRoute
  '/hoje': typeof HojeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/api/sports-api-maintenance': typeof ApiSportsApiMaintenanceRoute
  '/api/sports-daily-sync': typeof ApiSportsDailySyncRoute
  '/api/sports-jobs': typeof ApiSportsJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/anotacoes'
    | '/conta'
    | '/elo'
    | '/hoje'
    | '/privacidade'
    | '/api/elo-sync'
    | '/api/sports-api-maintenance'
    | '/api/sports-daily-sync'
    | '/api/sports-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/anotacoes'
    | '/conta'
    | '/elo'
    | '/hoje'
    | '/privacidade'
    | '/api/elo-sync'
    | '/api/sports-api-maintenance'
    | '/api/sports-daily-sync'
    | '/api/sports-jobs'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/anotacoes'
    | '/conta'
    | '/elo'
    | '/hoje'
    | '/privacidade'
    | '/api/elo-sync'
    | '/api/sports-api-maintenance'
    | '/api/sports-daily-sync'
    | '/api/sports-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnotacoesRoute: typeof AnotacoesRoute
  ContaRoute: typeof ContaRoute
  EloRoute: typeof EloRoute
  HojeRoute: typeof HojeRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ApiEloSyncRoute: typeof ApiEloSyncRoute
  ApiSportsApiMaintenanceRoute: typeof ApiSportsApiMaintenanceRoute
  ApiSportsDailySyncRoute: typeof ApiSportsDailySyncRoute
  ApiSportsJobsRoute: typeof ApiSportsJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elo': {
      id: '/elo'
      path: '/elo'
      fullPath: '/elo'
      preLoaderRoute: typeof EloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elo-sync': {
      id: '/api/elo-sync'
      path: '/api/elo-sync'
      fullPath: '/api/elo-sync'
      preLoaderRoute: typeof ApiEloSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sports-api-maintenance': {
      id: '/api/sports-api-maintenance'
      path: '/api/sports-api-maintenance'
      fullPath: '/api/sports-api-maintenance'
      preLoaderRoute: typeof ApiSportsApiMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sports-daily-sync': {
      id: '/api/sports-daily-sync'
      path: '/api/sports-daily-sync'
      fullPath: '/api/sports-daily-sync'
      preLoaderRoute: typeof ApiSportsDailySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sports-jobs': {
      id: '/api/sports-jobs'
      path: '/api/sports-jobs'
      fullPath: '/api/sports-jobs'
      preLoaderRoute: typeof ApiSportsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnotacoesRoute: AnotacoesRoute,
  ContaRoute: ContaRoute,
  EloRoute: EloRoute,
  HojeRoute: HojeRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ApiEloSyncRoute: ApiEloSyncRoute,
  ApiSportsApiMaintenanceRoute: ApiSportsApiMaintenanceRoute,
  ApiSportsDailySyncRoute: ApiSportsDailySyncRoute,
  ApiSportsJobsRoute: ApiSportsJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
