// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './database.types'
import { isAuthenticationFresh } from './session-policy'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_')
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    )

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value))
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization')
    }

    headers.set('apikey', supabaseKey)
    return fetch(input, { ...init, headers })
  }
}

async function isApprovedAppUser(
  supabaseUrl: string,
  supabaseKey: string,
  token: string,
): Promise<boolean> {
  try {
    const response = await fetch(
      `${supabaseUrl.replace(/\/$/, '')}/rest/v1/rpc/is_approved_app_user`,
      {
        method: 'POST',
        headers: {
          apikey: supabaseKey,
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: '{}',
      },
    )

    if (!response.ok) return false
    return (await response.json()) === true
  } catch {
    return false
  }
}

function deny(message: string): never {
  const error = new Error(message) as Error & { statusCode: number }
  error.statusCode = 401
  throw error
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env['SUPABASE_URL']
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY']

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ]
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`
      console.error(`[Supabase] ${message}`)
      throw new Error(message)
    }

    const request = getRequest()
    if (!request?.headers) deny('Unauthorized')

    const authHeader = request.headers.get('authorization')
    if (!authHeader?.startsWith('Bearer ')) deny('Unauthorized')

    const token = authHeader.slice('Bearer '.length).trim()
    if (!token || token.split('.').length !== 3) deny('Unauthorized')

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
        headers: { Authorization: `Bearer ${token}` },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    })

    const { data, error } = await supabase.auth.getClaims(token)
    if (error || !data?.claims) deny('Unauthorized')

    const claims = data.claims as Record<string, unknown>
    const userId = typeof claims['sub'] === 'string' ? claims['sub'] : ''
    const sessionId = typeof claims['session_id'] === 'string' ? claims['session_id'] : ''
    const appMetadata =
      typeof claims['app_metadata'] === 'object' && claims['app_metadata'] !== null
        ? (claims['app_metadata'] as Record<string, unknown>)
        : null
    const provider = typeof appMetadata?.['provider'] === 'string' ? appMetadata['provider'] : ''

    if (!userId || !sessionId || provider !== 'google') deny('Unauthorized')
    if (!isAuthenticationFresh(claims)) deny('Session expired. Reauthenticate with Google.')
    if (!(await isApprovedAppUser(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, token))) {
      deny('Unauthorized')
    }

    return next({
      context: {
        supabase,
        userId,
        claims: data.claims,
      },
    })
  },
)
